#!/bin/bash
#
# registration-ldap This script starts and stops the ApacheDS 
#       LDAP server for the 'cloud' partition.
#
# chkconfig: - 27 73
# description: LDAP support for StratusLab registration service
# processname: apacheds
# config: /var/lib/apacheds/cloud/apacheds.conf, server.xml
# pidfile: /var/run/apacheds/cloud/apacheds.pid

# Source function library.
. /etc/init.d/functions

RETVAL=0

conf_file=/etc/stratuslab/registration.cfg
rootaci_ldif=/var/lib/apacheds/cloud/rootACI.ldif

function extract_ldap_password() {
    ldap_password=`grep ldap.manager.password /etc/stratuslab/registration.cfg | cut -d = -f 2`
}


function reset_aci() {
    extract_ldap_password
    sleep 5
    ldapdelete -H ldap://localhost:10389  -x -D uid=admin,ou=system -w ${ldap_password} cn=rootACI,o=cloud
    ldapadd -H ldap://localhost:10389  -x -D uid=admin,ou=system -w ${ldap_password} -f ${rootaci_ldif}
}

function start() {
    /etc/init.d/apacheds start cloud

    # This is a workaround for a bug in ApacheDS where the 
    # server does not maintain the ACIs after a service
    # restart. 
    reset_aci
}

function stop() {
    /etc/init.d/apacheds stop cloud
}

function status() {
    /etc/init.d/apacheds status cloud
}

case "$1" in
    start)
	start
	RETVAL=$?
	;;
    stop)
	stop
	RETVAL=$?
	;;
    status)
	status ${slapd}
	RETVAL=$?
	;;
    restart)
	stop
	start
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=1
esac

exit $RETVAL
